name: "7 Timeframe"
on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '0 13 * * *'
  push:
    branches:
      - main

jobs:
  update-data:
    name: Update Dashboard
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Add Quarto to PATH
        run: |
          echo "export PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
      - run: |
          quarto --version
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - name: Apt-get needed things
        run: |
          sudo apt-get install --no-install-recommends -y \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev
      - run: echo "üçè This job's status is ${{ job.status }}."
      - name: "Install Packages"
        run: |
          install.packages('httr')
          install.packages('remotes')
          remotes::install_github('hadley/emo')
          install.packages('shiny')
          install.packages('scales')
          install.packages('treemap')
          install.packages('htmltools')
          install.packages('here')
          install.packages('jsonlite')
          install.packages('janitor')
          install.packages('quarto')
          install.packages('tidyverse')
          install.packages('highcharter')
          install.packages('openxlsx')
          install.packages('lubridate')
          install.packages('gt')
          install.packages('gtExtras')
        shell: Rscript {0}
      - name: "Script - Run"
        run: Rscript 'retrieve_targeting_data.R'
      - name: "Script - Update Dashboard"
        run: Rscript 'start.R'
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Script Routine Seven
